systemd: Restart service automatically after package upgrades (can be disabled)

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -55,4 +55,13 @@ chmod 0440 /etc/sudoers.d/"$APP_ID"
 # System user's directory permissions
 chown -RPh "$RUN_AS".daemon /var/log/"$APP_ID"/. /var/opt/"$APP_ID"/. /var/run/"$APP_ID"/.
 
+# Start service AFTER permissions etc. are fixed
+if [ "$1" = "configure" ]; then
+    if "${JUPYTERHUB_AUTO_RESTART:-false}"; then
+        echo "*** $APP_ID: Starting service..."
+        systemctl start "$APP_ID" \
+            || echo >&2 "!!! $APP_ID: Starting service failed (RC=$?), for details see journalctl"
+    fi
+fi
+
 exit 0
